"""
Opentrons adapter: Workflow -> OT-2 Python protocol + software simulation.

Chosen as the one real adapter for the MVP because `opentrons.simulate` runs a
real protocol in software with zero hardware — genuine validated execution on
stage. Incubations/waits and off-deck reads become comments or manual steps; the
liquid handling is real.

The SAME Workflow IR also compiles to an Echo picklist (see echo_adapter, an
afternoon of work) — one spoken sentence, two radically different outputs. That
contrast is the "universal" proof.
"""
from __future__ import annotations

import subprocess
import sys
import tempfile

from app.adapters.base import Adapter, Capabilities
from app.models.workflow import OpType, Workflow

_TYPE_MAP = {
    # platform-neutral token -> Opentrons load name
    "corning_96_wellplate_360ul": "corning_96_wellplate_360ul_flat",
    "nest_12_reservoir_15ml": "nest_12_reservoir_15ml",
    "opentrons_96_tiprack_300ul": "opentrons_96_tiprack_300ul",
}


class OpentronsAdapter(Adapter):
    capabilities = Capabilities(
        name="Opentrons OT-2",
        supported_ops={
            OpType.transfer, OpType.mix, OpType.wash,
            OpType.incubate, OpType.wait, OpType.move_labware, OpType.manual_step,
        },
        min_volume_uL=1.0,
        max_volume_uL=300.0,   # p300 single-channel ceiling for the loaded config
        needs_tips=True,
        labware_types=set(_TYPE_MAP.keys()),
    )

    def compile(self, wf: Workflow) -> str:
        lines: list[str] = []
        lines.append('"""Auto-generated by Lab Agent — do not hand-edit."""')
        lines.append("from opentrons import protocol_api\n")
        lines.append("metadata = {'apiLevel': '2.15', "
                     f"'protocolName': '{wf.source_sop or wf.workflow_id}'}}\n")
        lines.append("def run(protocol: protocol_api.ProtocolContext):")

        # Labware
        for lw in wf.labware:
            load = _TYPE_MAP.get(lw.type, lw.type)
            slot = lw.slot or "1"
            lines.append(f"    {lw.id} = protocol.load_labware('{load}', '{slot}')")

        # Pipette (single p300 for the MVP config)
        tip_ids = [lw.id for lw in wf.labware if lw.role == "tips"]
        tip_arg = f"tip_racks=[{tip_ids[0]}]" if tip_ids else ""
        lines.append(f"    pipette = protocol.load_instrument('p300_single_gen2', 'right', {tip_arg})\n")

        # Operations
        for op in wf.operations:
            if op.op == OpType.transfer and op.source and op.dest and op.volume:
                new_tip = "'always'" if op.new_tip else "'never'"
                src = f"{op.source.labware}['{op.source.well}']"
                dst = f"{op.dest.labware}['{op.dest.well}']"
                lines.append(f"    pipette.transfer({op.volume.to_uL()}, {src}, {dst}, new_tip={new_tip})")
            elif op.op == OpType.wash and op.dest:
                lines.append(f"    # WASH: {op.note or 'plate wash'} on {op.dest.labware} "
                             f"(3x aspirate/dispense wash buffer)")
            elif op.op == OpType.incubate:
                mins = (op.duration_s or 0) // 60
                temp = f" at {op.temperature_c}C" if op.temperature_c is not None else ""
                lines.append(f"    protocol.delay(minutes={mins})  # incubate{temp}")
            elif op.op == OpType.wait:
                lines.append(f"    protocol.delay(minutes={(op.duration_s or 0)//60})  # {op.note or 'wait'}")
            elif op.op == OpType.manual_step:
                lines.append(f"    protocol.pause('{op.note or 'manual step'}')")

        lines.append("")
        return "\n".join(lines)

    def simulate(self, wf: Workflow) -> tuple[bool, str]:
        """Run opentrons.simulate on the compiled protocol. Falls back to a dry
        summary if the opentrons package isn't installed in this environment."""
        protocol = self.compile(wf)
        import importlib.util
        if importlib.util.find_spec("opentrons") is None:
            return self._dry_summary(wf, reason="opentrons not installed")
        try:
            with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as fh:
                fh.write(protocol)
                path = fh.name
            proc = subprocess.run(
                [sys.executable, "-m", "opentrons.simulate", path],
                capture_output=True, text=True, timeout=120,
            )
            ok = proc.returncode == 0
            log = proc.stdout if ok else (proc.stdout + "\n" + proc.stderr)
            return ok, log.strip()
        except FileNotFoundError:
            return self._dry_summary(wf, reason="opentrons not installed")
        except Exception as e:  # pragma: no cover
            return self._dry_summary(wf, reason=f"simulate unavailable ({e})")

    def _dry_summary(self, wf: Workflow, reason: str) -> tuple[bool, str]:
        steps = [f"  - {op.describe()}" for op in wf.operations]
        header = (f"[dry-run summary — {reason}]\n"
                  f"Protocol {wf.workflow_id} ({wf.source_sop}), "
                  f"{len(wf.operations)} operations:")
        return True, header + "\n" + "\n".join(steps)
